spring.datasource.url=${NEON_JDBC_URL}
spring.datasource.username=${NEON_USERNAME}
spring.datasource.password=${NEON_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

!spring.datasource.url=jdbc:postgresql://51.159.114.168:61322/dev
!spring.datasource.username=bewize-dev
!spring.datasource.password=BeWize$DbDev2024 
!spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
slf4j.logger.org.hibernate.SQL=DEBUG